#!/bin/bash

warned=0
status=0

# colors
cyan="\e[0;36m"
red="\e[0;31m"
yellow="\e[0;33m"
green="\e[0;32m"
reset="\e[0m"

while read oldrev newrev refname; do
    echo -e "${cyan}Checking $puppetmodule for syntax errors and styleguide compliance...${reset}"

    for puppetmodule in `git diff-tree --no-commit-id --name-only -r $oldrev..$newrev`; do
        tmpdir=`mktemp -d`
        tmpmodule="$tmpdir/$puppetmodule"
        tmperror="$tmpdir/errors.txt"
        mkdir -p $tmpmodule
        rmdir $tmpmodule

        git show $newrev:$puppetmodule > $tmpmodule
        case $puppetmodule in
            *.pp )
                puppet parser validate $tmpmodule 2> $tmperror
                rc=$?
                if [[ $rc -ne 0 ]]; then
                    echo -e "${red}'puppet parser validate' failed on '${green}$puppetmodule${red}' - push denied. Run tests locally and confirm they pass before pushing.${reset}"
                    cat $tmperror
                    echo
                    status=1
                fi
                # Check styleguide, but do not error if styleguide does not pass
                /usr/bin/puppet-lint \
                    --fail-on-warnings \
                    --no-80chars-check \
                    --no-double_quoted_strings-check \
                    --no-arrow_alignment-check \
                    $tmpmodule > $tmperror
                rc=$?
                if [[ $rc -ne 0 ]]; then
                    if [[ $warned -eq 0 ]]; then
                        echo -e "${yellow}Please follow the puppet module styleguide (http://docs.puppetlabs.com/guides/style_guide.html).${reset}"
                        echo -e "${red}The following ERROR/WARNING messages are informational only. The commit has been accepted. In the future, these will cause your commit to be refused.${reset}"
                        warned=1
                    fi
                    echo -e "${yellow}Style guide compliance errors in ${green}$puppetmodule:${yellow}"
                    echo
                    cat $tmperror
                    echo -e "${reset}"
                fi
                ;;
            *.erb )
                cat $tmpmodule | erb -x -T - | ruby -c > /dev/null 2> $tmperror
                rc=$?
                if [[ $rc -ne 0 ]]; then
                    echo -e "${red}Ruby syntax checker failed on template '${green}${puppetmodule}${yellow}':"
                    echo
                    cat $tmperror
                    echo -e "${reset}"
                    status=1
                fi
                ;;
        esac
        rm -rf $tmpdir
    done
done

exit $status
